// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        (unknown)
// source: caso.proto

package main

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CasoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre        string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Departamento  string `protobuf:"bytes,2,opt,name=departamento,proto3" json:"departamento,omitempty"`
	Edad          int32  `protobuf:"varint,3,opt,name=edad,proto3" json:"edad,omitempty"`
	FormaContagio string `protobuf:"bytes,4,opt,name=forma_contagio,json=formaContagio,proto3" json:"forma_contagio,omitempty"`
	Estado        string `protobuf:"bytes,5,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *CasoRequest) Reset() {
	*x = CasoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_caso_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CasoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CasoRequest) ProtoMessage() {}

func (x *CasoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_caso_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CasoRequest.ProtoReflect.Descriptor instead.
func (*CasoRequest) Descriptor() ([]byte, []int) {
	return file_caso_proto_rawDescGZIP(), []int{0}
}

func (x *CasoRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *CasoRequest) GetDepartamento() string {
	if x != nil {
		return x.Departamento
	}
	return ""
}

func (x *CasoRequest) GetEdad() int32 {
	if x != nil {
		return x.Edad
	}
	return 0
}

func (x *CasoRequest) GetFormaContagio() string {
	if x != nil {
		return x.FormaContagio
	}
	return ""
}

func (x *CasoRequest) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type CasoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensaje string `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
}

func (x *CasoReply) Reset() {
	*x = CasoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_caso_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CasoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CasoReply) ProtoMessage() {}

func (x *CasoReply) ProtoReflect() protoreflect.Message {
	mi := &file_caso_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CasoReply.ProtoReflect.Descriptor instead.
func (*CasoReply) Descriptor() ([]byte, []int) {
	return file_caso_proto_rawDescGZIP(), []int{1}
}

func (x *CasoReply) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

var File_caso_proto protoreflect.FileDescriptor

var file_caso_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x63, 0x61, 0x73, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61,
	0x69, 0x6e, 0x22, 0x9c, 0x01, 0x0a, 0x0b, 0x43, 0x61, 0x73, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65,
	0x70, 0x61, 0x72, 0x74, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x65, 0x64, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x65, 0x64,
	0x61, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x5f, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x67, 0x69, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x67, 0x69, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74,
	0x61, 0x64, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64,
	0x6f, 0x22, 0x25, 0x0a, 0x09, 0x43, 0x61, 0x73, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x32, 0x39, 0x0a, 0x04, 0x43, 0x61, 0x73, 0x6f,
	0x12, 0x31, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x72, 0x43, 0x61, 0x73, 0x6f, 0x12, 0x11, 0x2e,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x61, 0x73, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0f, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x61, 0x73, 0x6f, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_caso_proto_rawDescOnce sync.Once
	file_caso_proto_rawDescData = file_caso_proto_rawDesc
)

func file_caso_proto_rawDescGZIP() []byte {
	file_caso_proto_rawDescOnce.Do(func() {
		file_caso_proto_rawDescData = protoimpl.X.CompressGZIP(file_caso_proto_rawDescData)
	})
	return file_caso_proto_rawDescData
}

var file_caso_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_caso_proto_goTypes = []interface{}{
	(*CasoRequest)(nil), // 0: main.CasoRequest
	(*CasoReply)(nil),   // 1: main.CasoReply
}
var file_caso_proto_depIdxs = []int32{
	0, // 0: main.Caso.CrearCaso:input_type -> main.CasoRequest
	1, // 1: main.Caso.CrearCaso:output_type -> main.CasoReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_caso_proto_init() }
func file_caso_proto_init() {
	if File_caso_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_caso_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CasoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_caso_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CasoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_caso_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_caso_proto_goTypes,
		DependencyIndexes: file_caso_proto_depIdxs,
		MessageInfos:      file_caso_proto_msgTypes,
	}.Build()
	File_caso_proto = out.File
	file_caso_proto_rawDesc = nil
	file_caso_proto_goTypes = nil
	file_caso_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CasoClient is the client API for Caso service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CasoClient interface {
	CrearCaso(ctx context.Context, in *CasoRequest, opts ...grpc.CallOption) (*CasoReply, error)
}

type casoClient struct {
	cc grpc.ClientConnInterface
}

func NewCasoClient(cc grpc.ClientConnInterface) CasoClient {
	return &casoClient{cc}
}

func (c *casoClient) CrearCaso(ctx context.Context, in *CasoRequest, opts ...grpc.CallOption) (*CasoReply, error) {
	out := new(CasoReply)
	err := c.cc.Invoke(ctx, "/main.Caso/CrearCaso", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CasoServer is the server API for Caso service.
type CasoServer interface {
	CrearCaso(context.Context, *CasoRequest) (*CasoReply, error)
}

// UnimplementedCasoServer can be embedded to have forward compatible implementations.
type UnimplementedCasoServer struct {
}

func (*UnimplementedCasoServer) CrearCaso(context.Context, *CasoRequest) (*CasoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrearCaso not implemented")
}

func RegisterCasoServer(s *grpc.Server, srv CasoServer) {
	s.RegisterService(&_Caso_serviceDesc, srv)
}

func _Caso_CrearCaso_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CasoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CasoServer).CrearCaso(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Caso/CrearCaso",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CasoServer).CrearCaso(ctx, req.(*CasoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Caso_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.Caso",
	HandlerType: (*CasoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrearCaso",
			Handler:    _Caso_CrearCaso_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "caso.proto",
}
